version: "2"

services: 
    posts:
        build: 
            context: .
            target: dev
          volumes:
            - .:/node/app:delegated
            - /node/app/node_modules
              